sonarqube:
    image: sonarqube
    restart: always
    ports:
        - "9092:9092"
        - "80:9000"
    environment:
        - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    links:
        - db

db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
    volumes:
        - /c/work-docker-db/sonar:/var/lib/postgresql